/**
 * WI-061 — Trip sheet scoping + DN PDF IRN parity.
 *
 * Two coupled bugs from 2026-05-16 manual testing:
 *   A. Trip sheet PDF was including delivered orders from earlier trips.
 *      Fix: filter status='pending_delivery' AND updatedAt >= DVA.updatedAt.
 *   B. DN PDF never rendered the IRN block even when the DBN IRN was
 *      successfully generated by processDebitNoteGst.
 *      Fix: mirror the CN PDF's CRN-block lookup (gst_documents
 *      docType='DBN', isLatest=true) and render via the now-shared
 *      drawCrnDetailsBox helper.
 *
 * Tests pin both fixes with PDFDocument.prototype.text spies because
 * pdfkit deflate-compresses content streams — raw buffer regex won't
 * match. Pattern lifted from invoice-list-badges-cn-pdf.test.ts.
 */
import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import request from 'supertest';

import { createApp } from '../app.js';
import { prisma } from '../lib/prisma.js';
import { generateToken } from './helpers.js';
import type { Express } from 'express';

let app: Express;
let sharmaAdminToken: string;

const auth = (t: string) => ({ Authorization: `Bearer ${t}` });

// Fixed far-future date isolates from real seed orders (anti-pattern #7).
const TRIP_DATE = new Date('2099-12-31');

beforeAll(async () => {
  app = createApp();
  const sharmaAdmin = await prisma.user.findUniqueOrThrow({
    where: { email: 'sharma@gasdist.com' },
  });
  sharmaAdminToken = generateToken({
    userId: sharmaAdmin.id,
    email: sharmaAdmin.email,
    role: sharmaAdmin.role as any,
    distributorId: sharmaAdmin.distributorId,
  });
});

afterAll(async () => {
  // Belt-and-braces cleanup — anything left behind by failed runs.
  await prisma.gstDocument.deleteMany({
    where: { gstDocNo: { startsWith: 'WI061-' } },
  });
  await prisma.debitNote.deleteMany({
    where: { debitNoteNumber: { startsWith: 'WI061-DN-' } },
  });
  await prisma.order.deleteMany({
    where: { orderNumber: { startsWith: 'WI061-ORD-' } },
  });
  await prisma.driverVehicleAssignment.deleteMany({
    where: { assignmentDate: TRIP_DATE },
  });
});

async function getValuedInvoice() {
  return prisma.invoice.findFirstOrThrow({
    where: {
      distributorId: 'dist-002',
      deletedAt: null,
      status: { not: 'cancelled' },
      totalAmount: { gt: 1000 },
    },
    orderBy: { createdAt: 'asc' },
  });
}

async function getDriverAndVehicle() {
  const driver = await prisma.driver.findFirstOrThrow({
    where: { distributorId: 'dist-002', deletedAt: null, status: 'active' },
  });
  const vehicle = await prisma.vehicle.findFirstOrThrow({
    where: { distributorId: 'dist-002', deletedAt: null },
  });
  return { driver, vehicle };
}

function spyDrawnStrings(PDFDocument: any) {
  const drawn: string[] = [];
  const original = PDFDocument.prototype.text;
  const spy = vi.spyOn(PDFDocument.prototype as any, 'text').mockImplementation(
    function (this: any, str: any, ...rest: any[]) {
      if (typeof str === 'string') drawn.push(str);
      return original.call(this, str, ...rest);
    },
  );
  return { drawn, spy };
}

// ─── Trip sheet ───────────────────────────────────────────────────────────────
describe('WI-061 — Trip sheet only includes current trip pending_delivery', () => {
  it('PDF excludes delivered orders from the same driver+date', async () => {
    const { driver, vehicle } = await getDriverAndVehicle();
    const customer = await prisma.customer.findFirstOrThrow({
      where: { distributorId: 'dist-002', deletedAt: null },
    });
    // Far-future DVA so the time-range filter is the only thing that
    // could include older orders.
    // Generate a unique trip_number per run to avoid colliding with the
    // new (driver, date, trip_number) unique constraint when tests are
    // re-run against the shared dev DB before the afterAll cleanup runs.
    const tripNumber = 1000 + Math.floor(Math.random() * 9000);
    const dva = await prisma.driverVehicleAssignment.create({
      data: {
        driverId: driver.id,
        vehicleId: vehicle.id,
        distributorId: 'dist-002',
        assignmentDate: TRIP_DATE,
        tripNumber,
        status: 'dispatch_ready',
      },
    });
    // Two delivered orders + one pending_delivery — same driver+date.
    const oDelivered = await prisma.order.create({
      data: {
        orderNumber: `WI061-ORD-DEL-${Date.now().toString(36)}`,
        distributorId: 'dist-002',
        customerId: customer.id,
        driverId: driver.id,
        vehicleId: vehicle.id,
        orderDate: TRIP_DATE,
        deliveryDate: TRIP_DATE,
        status: 'delivered',
        totalAmount: 100,
      },
    });
    const oPending = await prisma.order.create({
      data: {
        orderNumber: `WI061-ORD-PEND-${Date.now().toString(36)}`,
        distributorId: 'dist-002',
        customerId: customer.id,
        driverId: driver.id,
        vehicleId: vehicle.id,
        orderDate: TRIP_DATE,
        deliveryDate: TRIP_DATE,
        status: 'pending_delivery',
        totalAmount: 100,
      },
    });
    // Give the pending order an EWB so the route doesn't 400.
    await prisma.gstDocument.create({
      data: {
        orderId: oPending.id,
        distributorId: 'dist-002',
        docType: 'INV',
        gstDocNo: `WI061-EWB-${Date.now().toString(36)}`,
        ewbStatus: 'active',
        ewbNo: '999999999999',
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/orders/trip-sheet/${dva.id}`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(res.headers['content-type']).toContain('application/pdf');

      // The pending order's number must appear; the delivered one must NOT.
      expect(drawn.some((s) => s.includes(oPending.orderNumber))).toBe(true);
      expect(drawn.some((s) => s.includes(oDelivered.orderNumber))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.deleteMany({ where: { orderId: oPending.id } });
      await prisma.order.deleteMany({ where: { id: { in: [oDelivered.id, oPending.id] } } });
      await prisma.driverVehicleAssignment.delete({ where: { id: dva.id } });
    }
  });

  it('returns 400 when the route has no in-transit orders at all', async () => {
    const { driver, vehicle } = await getDriverAndVehicle();
    const tripNumber = 1000 + Math.floor(Math.random() * 9000);
    const dva = await prisma.driverVehicleAssignment.create({
      data: {
        driverId: driver.id,
        vehicleId: vehicle.id,
        distributorId: 'dist-002',
        assignmentDate: TRIP_DATE,
        tripNumber,
        status: 'dispatch_ready',
      },
    });
    try {
      const res = await request(app)
        .get(`/api/orders/trip-sheet/${dva.id}`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(400);
    } finally {
      await prisma.driverVehicleAssignment.delete({ where: { id: dva.id } });
    }
  });
});

// ─── DN PDF IRN parity ────────────────────────────────────────────────────────
describe('WI-061 — Debit Note PDF renders IRN block from gst_documents', () => {
  it('writes the IRN string when a DBN gst_documents row has irnStatus=success', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-OK-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF IRN success path',
        status: 'pending_dn',
      },
    });
    const fakeIrn = 'd'.repeat(64);
    const dbnDoc = await prisma.gstDocument.create({
      data: {
        invoiceId: inv.id,
        distributorId: 'dist-002',
        docType: 'DBN',
        gstDocNo: `WI061-DOC-${Date.now().toString(36)}`,
        irnStatus: 'success',
        irn: fakeIrn,
        ackNo: '112612345678901',
        ackDate: new Date(),
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      // The IRN box title + the IRN string itself must both be drawn.
      expect(drawn.some((s) => /DBN Details - IRN/.test(s))).toBe(true);
      // IRN is rendered split across lines by formatIrnForDisplay,
      // so search for any line that contains a long-ish prefix.
      const irnPrefix = fakeIrn.slice(0, 16);
      expect(drawn.some((s) => s.includes(irnPrefix))).toBe(true);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.delete({ where: { id: dbnDoc.id } });
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('writes "Pending generation" when no DBN row exists', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-PEND-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF pending path',
        status: 'pending_dn',
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(drawn.some((s) => /e-Invoice \(IRN\): Pending generation/.test(s))).toBe(true);
      expect(drawn.some((s) => /e-Invoice \(IRN\): Generation failed/.test(s))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('writes "Generation failed — retry from Billing page" when DBN row has irnStatus=failed', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-FAIL-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF failed path',
        status: 'pending_dn',
      },
    });
    const dbnDoc = await prisma.gstDocument.create({
      data: {
        invoiceId: inv.id,
        distributorId: 'dist-002',
        docType: 'DBN',
        gstDocNo: `WI061-DOC-FAIL-${Date.now().toString(36)}`,
        irnStatus: 'failed',
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(drawn.some((s) => /e-Invoice \(IRN\): Generation failed/.test(s))).toBe(true);
      expect(drawn.some((s) => /retry from Billing page/.test(s))).toBe(true);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.delete({ where: { id: dbnDoc.id } });
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('footer wording aligned with CN PDF ("computer generated <kind> note.")', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-FOOT-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF footer test',
        status: 'pending_dn',
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(drawn.some((s) => /computer generated debit note/i.test(s))).toBe(true);
      // The pre-WI-061 wording must be gone.
      expect(drawn.some((s) => /does not require a signature/.test(s))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });
});
