/**
 * WI-061 — Trip sheet scoping + DN PDF IRN parity.
 *
 * Two coupled bugs from 2026-05-16 manual testing:
 *   A. Trip sheet PDF was including delivered orders from earlier trips.
 *      Fix: filter status='pending_delivery' AND updatedAt >= DVA.updatedAt.
 *   B. DN PDF never rendered the IRN block even when the DBN IRN was
 *      successfully generated by processDebitNoteGst.
 *      Fix: mirror the CN PDF's CRN-block lookup (gst_documents
 *      docType='DBN', isLatest=true) and render via the now-shared
 *      drawCrnDetailsBox helper.
 *
 * Tests pin both fixes with PDFDocument.prototype.text spies because
 * pdfkit deflate-compresses content streams — raw buffer regex won't
 * match. Pattern lifted from invoice-list-badges-cn-pdf.test.ts.
 */
import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import request from 'supertest';

import { createApp } from '../app.js';
import { prisma } from '../lib/prisma.js';
import { generateToken } from './helpers.js';
import type { Express } from 'express';
import type { UserRole } from '@gaslink/shared';
import type PDFKitCtor from 'pdfkit';

let app: Express;
let sharmaAdminToken: string;

const auth = (t: string) => ({ Authorization: `Bearer ${t}` });

// Fixed far-future date isolates from real seed orders (anti-pattern #7).
const TRIP_DATE = new Date('2099-12-31');

// Self-seeded fixture invoice — avoids reliance on pre-existing DB data
// (anti-pattern #7 fix). Created in beforeAll, deleted in afterAll.
let fixtureInvoiceId: string | null = null;

beforeAll(async () => {
  app = createApp();
  const sharmaAdmin = await prisma.user.findUniqueOrThrow({
    where: { email: 'sharma@gasdist.com' },
  });
  sharmaAdminToken = generateToken({
    userId: sharmaAdmin.id,
    email: sharmaAdmin.email,
    role: sharmaAdmin.role as UserRole,
    distributorId: sharmaAdmin.distributorId,
  });

  // Seed a fixture invoice so getValuedInvoice() always finds one regardless
  // of whether cleanup-dist002-seed.ts has been run.
  const customer = await prisma.customer.findFirstOrThrow({
    where: { distributorId: 'dist-002', deletedAt: null },
  });
  const fixture = await prisma.invoice.create({
    data: {
      invoiceNumber: `WI061-FIXTURE-${Date.now()}`,
      distributorId: 'dist-002',
      customerId: customer.id,
      issueDate: new Date(),
      dueDate: new Date(),
      totalAmount: 5000,
      amountPaid: 0,
      outstandingAmount: 5000,
      status: 'issued',
    },
  });
  fixtureInvoiceId = fixture.id;
});

afterAll(async () => {
  // Belt-and-braces cleanup — anything left behind by failed runs.
  await prisma.gstDocument.deleteMany({
    where: { gstDocNo: { startsWith: 'WI061-' } },
  });
  await prisma.debitNote.deleteMany({
    where: { debitNoteNumber: { startsWith: 'WI061-DN-' } },
  });
  await prisma.debitNote.deleteMany({
    where: { debitNoteNumber: { startsWith: 'WI077-DN-' } },
  });
  await prisma.order.deleteMany({
    where: { orderNumber: { startsWith: 'WI061-ORD-' } },
  });
  await prisma.driverVehicleAssignment.deleteMany({
    where: { assignmentDate: TRIP_DATE },
  });
  // Remove fixture invoice (and any debit notes/gst docs the tests created on it).
  if (fixtureInvoiceId) {
    await prisma.gstDocument.deleteMany({ where: { invoiceId: fixtureInvoiceId } });
    await prisma.debitNote.deleteMany({ where: { invoiceId: fixtureInvoiceId } });
    await prisma.invoice.delete({ where: { id: fixtureInvoiceId } }).catch(() => {});
    fixtureInvoiceId = null;
  }
});

async function getValuedInvoice() {
  // Returns the self-seeded fixture invoice — no longer depends on pre-existing
  // DB data (anti-pattern #7 fix).
  return prisma.invoice.findUniqueOrThrow({ where: { id: fixtureInvoiceId! } });
}

async function getDriverAndVehicle() {
  const driver = await prisma.driver.findFirstOrThrow({
    where: { distributorId: 'dist-002', deletedAt: null, status: 'active' },
  });
  const vehicle = await prisma.vehicle.findFirstOrThrow({
    where: { distributorId: 'dist-002', deletedAt: null },
  });
  return { driver, vehicle };
}

type PDFDoc = InstanceType<typeof PDFKitCtor>;

function spyDrawnStrings(PDFDocument: typeof PDFKitCtor) {
  const drawn: string[] = [];
  const original = PDFDocument.prototype.text as (...args: unknown[]) => PDFDoc;
  const spy = vi.spyOn(PDFDocument.prototype, 'text').mockImplementation(
    function (this: PDFDoc, ...args: unknown[]) {
      if (typeof args[0] === 'string') drawn.push(args[0]);
      return original.apply(this, args);
    },
  );
  return { drawn, spy };
}

// ─── Trip sheet ───────────────────────────────────────────────────────────────
describe('WI-061 — Trip sheet only includes current trip pending_delivery', () => {
  it('PDF excludes delivered orders from the same driver+date', async () => {
    const { driver, vehicle } = await getDriverAndVehicle();
    const customer = await prisma.customer.findFirstOrThrow({
      where: { distributorId: 'dist-002', deletedAt: null },
    });
    // Far-future DVA so the time-range filter is the only thing that
    // could include older orders.
    // Generate a unique trip_number per run to avoid colliding with the
    // new (driver, date, trip_number) unique constraint when tests are
    // re-run against the shared dev DB before the afterAll cleanup runs.
    const tripNumber = 1000 + Math.floor(Math.random() * 9000);
    const dva = await prisma.driverVehicleAssignment.create({
      data: {
        driverId: driver.id,
        vehicleId: vehicle.id,
        distributorId: 'dist-002',
        assignmentDate: TRIP_DATE,
        tripNumber,
        status: 'dispatch_ready',
      },
    });
    // Two delivered orders + one pending_delivery — same driver+date.
    const oDelivered = await prisma.order.create({
      data: {
        orderNumber: `WI061-ORD-DEL-${Date.now().toString(36)}`,
        distributorId: 'dist-002',
        customerId: customer.id,
        driverId: driver.id,
        vehicleId: vehicle.id,
        orderDate: TRIP_DATE,
        deliveryDate: TRIP_DATE,
        status: 'delivered',
        totalAmount: 100,
      },
    });
    const oPending = await prisma.order.create({
      data: {
        orderNumber: `WI061-ORD-PEND-${Date.now().toString(36)}`,
        distributorId: 'dist-002',
        customerId: customer.id,
        driverId: driver.id,
        vehicleId: vehicle.id,
        orderDate: TRIP_DATE,
        deliveryDate: TRIP_DATE,
        status: 'pending_delivery',
        totalAmount: 100,
      },
    });
    // Give the pending order an EWB so the route doesn't 400.
    await prisma.gstDocument.create({
      data: {
        orderId: oPending.id,
        distributorId: 'dist-002',
        docType: 'INV',
        gstDocNo: `WI061-EWB-${Date.now().toString(36)}`,
        ewbStatus: 'active',
        ewbNo: '999999999999',
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/orders/trip-sheet/${dva.id}`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(res.headers['content-type']).toContain('application/pdf');

      // The pending order's number must appear; the delivered one must NOT.
      expect(drawn.some((s) => s.includes(oPending.orderNumber))).toBe(true);
      expect(drawn.some((s) => s.includes(oDelivered.orderNumber))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.deleteMany({ where: { orderId: oPending.id } });
      await prisma.order.deleteMany({ where: { id: { in: [oDelivered.id, oPending.id] } } });
      await prisma.driverVehicleAssignment.delete({ where: { id: dva.id } });
    }
  });

  it('returns 200 with "EWB Pending" Trip Summary PDF when the route has no in-transit orders (WI-065)', async () => {
    // WI-065: the hard 400 here was demoted to a "Trip Summary — EWB
    // Pending" PDF. The web Driver Assignment tab's "📄 Trip Sheet"
    // button is now always actionable post-dispatch; producing a
    // checklist-style PDF beats an opaque 400.
    const { driver, vehicle } = await getDriverAndVehicle();
    const tripNumber = 1000 + Math.floor(Math.random() * 9000);
    const dva = await prisma.driverVehicleAssignment.create({
      data: {
        driverId: driver.id,
        vehicleId: vehicle.id,
        distributorId: 'dist-002',
        assignmentDate: TRIP_DATE,
        tripNumber,
        status: 'dispatch_ready',
      },
    });
    try {
      const res = await request(app)
        .get(`/api/orders/trip-sheet/${dva.id}`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(res.headers['content-type']).toMatch(/application\/pdf/);
      expect(res.body.slice(0, 4).toString()).toBe('%PDF');
    } finally {
      await prisma.driverVehicleAssignment.delete({ where: { id: dva.id } });
    }
  });
});

// ─── DN PDF IRN parity ────────────────────────────────────────────────────────
describe('WI-061 — Debit Note PDF renders IRN block from gst_documents', () => {
  it('writes the IRN string when a DBN gst_documents row has irnStatus=success', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-OK-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF IRN success path',
        status: 'pending_dn',
      },
    });
    const fakeIrn = 'd'.repeat(64);
    const dbnDoc = await prisma.gstDocument.create({
      data: {
        invoiceId: inv.id,
        distributorId: 'dist-002',
        docType: 'DBN',
        gstDocNo: `WI061-DOC-${Date.now().toString(36)}`,
        irnStatus: 'success',
        irn: fakeIrn,
        ackNo: '112612345678901',
        ackDate: new Date(),
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      // The IRN box title + the IRN string itself must both be drawn.
      expect(drawn.some((s) => /DBN Details - IRN/.test(s))).toBe(true);
      // IRN is rendered split across lines by formatIrnForDisplay,
      // so search for any line that contains a long-ish prefix.
      const irnPrefix = fakeIrn.slice(0, 16);
      expect(drawn.some((s) => s.includes(irnPrefix))).toBe(true);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.delete({ where: { id: dbnDoc.id } });
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('WI-077 — skips the IRN block on the DN PDF when no DBN row exists', async () => {
    // WI-077: B2C debit notes never get an IRN — the PDF should not
    // emit the legacy "Pending generation" status line. Mirror invoice
    // PDF behaviour and omit the compliance section entirely.
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI077-DN-NOIRN-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF WI-077 no-irn path',
        status: 'pending_dn',
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      // "Pending generation" / "Generation failed" labels are gone.
      expect(drawn.some((s) => /Pending generation/.test(s))).toBe(false);
      expect(drawn.some((s) => /Generation failed/.test(s))).toBe(false);
      // The DBN-Details header from drawCrnDetailsBox is also absent.
      expect(drawn.some((s) => /DBN Details/i.test(s))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('WI-077 — skips the IRN block when DBN row has irnStatus=failed and no IRN/EWB on it', async () => {
    // WI-077: a failed-status row with no IRN/EWB no longer renders the
    // red "retry from Billing page" line. Issuer sees the failure in
    // the Billing list + pending actions; the recipient PDF stays clean.
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI077-DN-FAIL-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF WI-077 failed-no-irn path',
        status: 'pending_dn',
      },
    });
    const dbnDoc = await prisma.gstDocument.create({
      data: {
        invoiceId: inv.id,
        distributorId: 'dist-002',
        docType: 'DBN',
        gstDocNo: `WI077-DOC-FAIL-${Date.now().toString(36)}`,
        irnStatus: 'failed',
        isLatest: true,
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      expect(drawn.some((s) => /Generation failed/.test(s))).toBe(false);
      expect(drawn.some((s) => /retry from Billing page/.test(s))).toBe(false);
      expect(drawn.some((s) => /DBN Details/i.test(s))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.gstDocument.delete({ where: { id: dbnDoc.id } });
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });

  it('footer wording aligned with CN PDF (self-authorising, no-signature)', async () => {
    const inv = await getValuedInvoice();
    const dn = await prisma.debitNote.create({
      data: {
        invoiceId: inv.id,
        debitNoteNumber: `WI061-DN-FOOT-${Date.now().toString(36)}`,
        totalAmount: 100,
        reason: 'DN PDF footer test',
        status: 'pending_dn',
      },
    });

    const PDFDocument = (await import('pdfkit')).default;
    const { drawn, spy } = spyDrawnStrings(PDFDocument);
    try {
      const res = await request(app)
        .get(`/api/invoices/debit-notes/${dn.id}/pdf`)
        .set(auth(sharmaAdminToken));
      expect(res.status).toBe(200);
      // 2026-07-19: footer switched from "computer generated debit
      // note." to a self-authorising disclaimer ("authorised,
      // auto-generated debit note" + "no signature or stamp required").
      expect(drawn.some((s) => /authorised,? auto-generated debit note/i.test(s))).toBe(true);
      expect(drawn.some((s) => /no signature or stamp is required/i.test(s))).toBe(true);
      // The pre-WI-061 wording must still be gone.
      expect(drawn.some((s) => /does not require a signature/.test(s))).toBe(false);
    } finally {
      spy.mockRestore();
      await prisma.debitNote.delete({ where: { id: dn.id } });
    }
  });
});
