/**
 * IRN / EWB payload shape validation.
 *
 * These tests run buildIrnPayload / buildEwbPayload directly against
 * synthetic InvoiceData fixtures and assert the SHAPE of the returned
 * payload — field names, lengths, formats, required keys, AND the
 * absence of fields that NIC rejects. They never touch the database,
 * never call WhiteBooks, and never spin up an Express app.
 *
 * Why this file exists (CLAUDE.md anti-patterns #6, #9, #10):
 *   Mocked unit + integration tests cover service logic but never
 *   see the raw payload NIC actually validates. The inline-EwbDtls
 *   regression on 2026-05-15 is the canonical example — every mock
 *   test passed; the live sandbox returned 5002 on first dispatch.
 *
 * Rule: every new WhiteBooks API path adds a payload-shape test here
 * that asserts the OUTGOING field structure against the WhiteBooks
 * Postman canonical, including the negative case (fields that must
 * NOT appear).
 */

import { describe, it, expect } from 'vitest';
import { buildIrnPayload, buildEwbPayload } from '../services/gst/payloadBuilders.js';

/**
 * Minimal B2B invoice fixture. No transport — inline EwbDtls support
 * was removed on 2026-05-15 after the live sandbox rejected every
 * variant; the IRN call must never carry an EwbDtls block. EWB is
 * generated by a separate call via buildEwbPayload.
 */
function b2bFixture(overrides: Partial<Parameters<typeof buildIrnPayload>[0]> = {}) {
  return {
    docType: 'INV' as const,
    docNumber: 'INV-MP6QW1RV8HJ',
    docDate: new Date('2026-05-15T00:00:00Z'),
    seller: {
      gstin: '29AAGCB1286Q000',
      legalName: 'Sharma Gas Distributors',
      tradeName: 'Sharma Gas',
      address: '123 Depot Road',
      city: 'Bangalore',
      pincode: '560001',
      state: 'Karnataka',
      stateCode: '29',
      phone: '9800000000',
      email: 'sharma@gasdist.com',
    },
    buyer: {
      gstin: '29AWGPV7107B1Z1',
      legalName: 'Maruthi Agencies',
      tradeName: 'Maruthi',
      address: '45 Customer Lane',
      city: 'Bangalore',
      pincode: '560041',
      state: 'Karnataka',
      stateCode: '29',
      phone: '9800000001',
      email: 'maruthi@example.com',
    },
    items: [{
      slNo: 1,
      description: '19 KG LPG Cylinder',
      hsnCode: '27111900',
      quantity: 5,
      unit: 'NOS',
      unitPrice: 2000,
      discountPerUnit: 0,
      gstRate: 18,
    }],
    isInterState: false,
    ...overrides,
  };
}

describe('IRN payload shape validation (NIC /einvoice GENERATE)', () => {
  it('CRITICAL — IRN payload MUST NOT contain EwbDtls', () => {
    // The single most important guard in this file. Inline EwbDtls
    // was rejected by NIC sandbox with generic 5002. Two-step flow:
    // IRN (no EwbDtls) → separate /ewaybillapi/.../genewaybill call.
    const payload = buildIrnPayload(b2bFixture());
    expect(payload.EwbDtls).toBeUndefined();
    expect(Object.keys(payload)).not.toContain('EwbDtls');
  });

  it('IRN payload also excludes any transport-prefixed fields at top level', () => {
    // Defence in depth against future drift — no stray transport hints
    // should leak into the IRN payload.
    const payload = buildIrnPayload(b2bFixture());
    const keys = Object.keys(payload);
    for (const k of keys) {
      expect(k).not.toMatch(/^(Trans|Veh|Distance)/);
    }
  });

  it('Required IRN top-level fields are all present', () => {
    const payload = buildIrnPayload(b2bFixture());
    expect(payload.TranDtls).toBeTruthy();
    expect(payload.DocDtls).toBeTruthy();
    expect(payload.SellerDtls).toBeTruthy();
    expect(payload.BuyerDtls).toBeTruthy();
    expect(payload.ItemList).toBeTruthy();
    expect(payload.ValDtls).toBeTruthy();
  });

  it('DocDtls contains No / Dt / Typ in correct shapes', () => {
    const payload = buildIrnPayload(b2bFixture());
    expect(typeof payload.DocDtls.No).toBe('string');
    expect(payload.DocDtls.No.length).toBeGreaterThan(0);
    expect(payload.DocDtls.No.length).toBeLessThanOrEqual(16); // NIC InvNo max
    expect(typeof payload.DocDtls.Dt).toBe('string');
    expect(payload.DocDtls.Dt).toMatch(/^\d{2}\/\d{2}\/\d{4}$/);
    expect(['INV', 'CRN', 'DBN']).toContain(payload.DocDtls.Typ);
  });

  it('TranDtls.SupTyp correctly reflects B2B vs B2C', () => {
    const b2b = buildIrnPayload(b2bFixture());
    expect(['B2B', 'SEZWP', 'SEZWOP', 'EXPWP', 'EXPWOP']).toContain(b2b.TranDtls.SupTyp);

    const b2c = buildIrnPayload(b2bFixture({
      buyer: { ...b2bFixture().buyer, gstin: null },
    }));
    expect(b2c.TranDtls.SupTyp).toBe('B2C');
  });

  it('ItemList is a non-empty array with HsnCd as string', () => {
    const payload = buildIrnPayload(b2bFixture());
    expect(Array.isArray(payload.ItemList)).toBe(true);
    expect(payload.ItemList.length).toBeGreaterThanOrEqual(1);
    expect(typeof payload.ItemList[0].HsnCd).toBe('string');
  });

  it('SellerDtls + BuyerDtls carry the expected fields', () => {
    const payload = buildIrnPayload(b2bFixture());
    expect(payload.SellerDtls.Gstin).toBeTruthy();
    expect(payload.SellerDtls.LglNm).toBeTruthy();
    expect(typeof payload.SellerDtls.Pin).toBe('number');
    expect(payload.SellerDtls.Stcd).toBeTruthy();
    expect(payload.BuyerDtls.Gstin).toBeTruthy();
    expect(payload.BuyerDtls.Pos).toBeTruthy();
  });
});

describe('EWB payload shape validation (NIC /ewaybillapi genewaybill — separate call after IRN)', () => {
  it('EWB payload is built separately from IRN — IRN reference is copied via docNo, not the whole IRN payload', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999',
      transportMode: '1',
      distance: 1,
    });
    // EWB has its own top-level fields, not nested under IRN.
    expect(ewb).not.toHaveProperty('TranDtls');
    expect(ewb).not.toHaveProperty('DocDtls');
    expect(ewb).not.toHaveProperty('SellerDtls');
    // It carries its own copy of the doc reference.
    expect(ewb.docNo).toBe(irn.DocDtls.No);
    expect(ewb.docDate).toBe(irn.DocDtls.Dt);
  });

  it('transDocNo is non-empty and within 15 chars', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999',
      transportMode: '1',
      distance: 1,
    });
    expect(typeof ewb.transDocNo).toBe('string');
    expect(ewb.transDocNo.length).toBeGreaterThanOrEqual(1);
    expect(ewb.transDocNo.length).toBeLessThanOrEqual(15);
  });

  it('transDocDate matches DD/MM/YYYY', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999',
      transportMode: '1',
      distance: 1,
    });
    expect(ewb.transDocDate).toMatch(/^\d{2}\/\d{2}\/\d{4}$/);
  });

  it('transMode defaults to "1" (road) and transDistance is >=1 string', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999',
      // transportMode omitted
      distance: 0, // EWB-side clamps to 1 (0 triggers NIC error 721)
    });
    expect(ewb.transMode).toBe('1');
    expect(typeof ewb.transDistance).toBe('string');
    expect(parseInt(ewb.transDistance, 10)).toBeGreaterThanOrEqual(1);
  });

  it('vehicleNo is sanitised to uppercase alphanumeric, max 15 chars', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'ka 01-mn / 9999',
      transportMode: '1',
      distance: 1,
    });
    expect(ewb.vehicleNo).toMatch(/^[A-Z0-9]+$/);
    expect(ewb.vehicleNo.length).toBeLessThanOrEqual(15);
  });

  // ─── WI-057 payload-shape guards ──────────────────────────────────────────
  //
  // The fixes in WI-057 close two NIC-rejection paths that mock tests
  // had no way to catch (anti-pattern #6). Pin them here so a future
  // edit that re-introduces the bug fails CI before it can ship.

  it('WI-057 G1 — transactionType is always 1 (Regular) for B2B', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999', transportMode: '1', distance: 1,
    });
    expect(ewb.transactionType).toBe(1);
  });

  it('WI-057 G1 — transactionType is always 1 (Regular) for B2C too', () => {
    // B2C fixture: drop buyer GSTIN so buildIrnPayload picks SupTyp=B2C.
    const irn = buildIrnPayload(b2bFixture({
      buyer: { ...b2bFixture().buyer, gstin: null },
    }));
    expect(irn.TranDtls.SupTyp).toBe('B2C');
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999', transportMode: '1', distance: 1,
    });
    // Prior bug: B2C set transactionType=2 ("Bill To ≠ Ship To") which
    // tripped NIC 611. For LPG the same customer is always both, so
    // Regular=1 is the only correct value regardless of B2B/B2C.
    expect(ewb.transactionType).toBe(1);
  });

  it('WI-057 — vehicleNo strips hyphens / slashes / spaces (NIC regex disallows them)', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01-MN-9999',
      transportMode: '1',
      distance: 1,
    });
    expect(ewb.vehicleNo).toBe('KA01MN9999');
    expect(ewb.vehicleNo).not.toMatch(/[-\s/]/);
  });

  it('WI-057 — vehicleNo uppercase regardless of input case', () => {
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'ka01mn9999',
      transportMode: '1',
      distance: 1,
    });
    expect(ewb.vehicleNo).toBe('KA01MN9999');
  });

  it('WI-070 — transDistance comes from pincode lookup; caller-passed distance is a no-op', () => {
    // Historical context: WI-057 introduced a `Math.max(1, distance || 1)`
    // clamp on the caller-supplied `distance` argument. WI-067 replaced
    // that with a pincode-derived value (`getTransDistance(fromPin, toPin)`)
    // so `transportDetails.distance` is now unused. WI-070 added a 1.15×
    // road-circuity factor on top.
    //
    // The fixture has seller.pincode=560001 and buyer.pincode=560041 —
    // both Bangalore, both share the city centroid in our table, so
    // Haversine ≈ 0 km → getDistanceKm floors to 1 → × 1.15 → ceil → 2.
    // What matters is NOT the exact number; it's the contract: the
    // caller's `distance: 0` argument has zero influence, and the
    // result is a positive integer string.
    const irn = buildIrnPayload(b2bFixture());
    const ewb = buildEwbPayload(irn, {
      vehicleNumber: 'KA01MN9999', transportMode: '1', distance: 0,
    });
    expect(typeof ewb.transDistance).toBe('string');
    expect(parseInt(ewb.transDistance, 10)).toBeGreaterThanOrEqual(1);
    expect(parseInt(ewb.transDistance, 10)).toBeLessThanOrEqual(4000);
  });

  it('WI-064 — DocDtls.No surfaces the bumped doc number, never silently reuses the burned original', () => {
    // After a cancel + reissue cycle, gstReissueService passes the
    // BUMPED invoice number (e.g. INV-XYZ-R1) as docNumber. The payload
    // builder must surface that bumped value verbatim — NIC remembers
    // the original as cancelled (2278) and will reject any payload that
    // silently reverts to the pre-bump value. Guards against future
    // refactors where docNumber might be re-derived from a different
    // source (invoice row, order, etc).
    //
    // NIC caps DocDtls.No at 16 chars (truncateDocNumber). Both forms
    // here fit within the cap so the test is deterministic.
    const bumped = 'INV-MPC38K5-R1';   // 14 chars
    const original = 'INV-MPC38K5';     // 11 chars — the "burned" pre-bump form
    const payload = buildIrnPayload(b2bFixture({ docNumber: bumped }));
    expect(payload.DocDtls.No).toBe(bumped);
    // The original burned number does NOT appear in the payload as a
    // standalone string value. Substring-search would match the base
    // inside the bumped form, so we check for the quote-wrapped form
    // JSON would emit if `original` were a value.
    const flat = JSON.stringify(payload);
    expect(flat).not.toContain(`"${original}"`);
  });
});
