/**
 * Config plugin: OS-native SSL certificate pinning for api.mygaslink.com.
 *
 * Why OS-native (no library): Android's network_security_config `<pin-set>`
 * (API 24+, our minSdk is 24) and iOS's `NSPinnedDomains` (iOS 14+, our
 * floor is 15) enforce SPKI pinning at the OS TLS layer for ALL traffic —
 * axios, fetch, SSE, image loads — with zero native modules. That keeps the
 * store-review surface unchanged (no new native code) and means we cannot
 * drift out of sync with the app's own HTTP stack.
 *
 * Pin strategy (decided 2026-08-07, see docs/RUNBOOK-CERT-ROTATION.md):
 * prod TLS is Let's Encrypt (issuer chain leaf → LE "YE1" → ISRG Root YE →
 * ISRG Root X2 → ISRG Root X1). LE leaf certs rotate every ~90 days and
 * certbot generates a NEW private key each renewal by default, so leaf SPKI
 * pinning would brick the app every rotation. Instead we pin the three
 * ISRG-owned ROOT public keys (X1 valid→2035, X2 →2040, Root YE →2032).
 * Root pins survive every leaf/intermediate rotation while still defeating
 * captive portals, corporate SSL-inspection proxies, and rogue/compromised
 * non-LE CAs — all of which must present a chain anchored outside ISRG.
 *
 * Enforcement gate: the plugin is a NO-OP unless the env var
 * `SSL_PINNING=true` is present at prebuild time. eas.json sets it for the
 * `preview` and `production` profiles only — local `expo prebuild`, the
 * `development` profile, and Expo Go are never pinned (Metro/LAN-IP dev
 * traffic is plain http and must not be interfered with).
 *
 * Android dead-man switch: `<pin-set expiration="...">` makes pinning fail
 * OPEN (falls back to normal CA validation) after that date, so a worst-case
 * "we stopped shipping updates" scenario degrades to today's behaviour
 * instead of bricking installs. iOS has no equivalent attribute — mitigated
 * by pinning only decade-stable ISRG roots.
 *
 * Verify after prebuild (with SSL_PINNING=true set):
 *   cd packages/mobile
 *   SSL_PINNING=true npx expo prebuild --clean --platform android --no-install
 *   cat android/app/src/main/res/xml/network_security_config.xml
 *   grep networkSecurityConfig android/app/src/main/AndroidManifest.xml
 * And without the env var: the XML file must NOT exist.
 */
const { withAndroidManifest, withInfoPlist, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const DEFAULTS = {
  domain: 'api.mygaslink.com',
  includeSubdomains: false,
  // Android-only fail-open date (YYYY-MM-DD). Renew alongside cert rotations
  // per docs/RUNBOOK-CERT-ROTATION.md.
  expiration: '2027-11-01',
  // SPKI SHA-256, Base64. Extracted + verified 2026-08-07 against both the
  // live api.mygaslink.com chain and https://letsencrypt.org/certs/.
  pins: [
    'C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=', // ISRG Root X1 (→2035)
    'diGVwiVYbubAI3RW4hB9xU8e/CH2GnkuvVFZE8zmgzI=', // ISRG Root X2 (→2040)
    'sCkq5UWXjg+7mKu9lMhhYF5bGLsy7VI/UNW3tccdR7w=', // ISRG Root YE (→2032)
  ],
};

function pinningEnabled() {
  return process.env.SSL_PINNING === 'true';
}

function buildNetworkSecurityXml({ domain, includeSubdomains, expiration, pins }) {
  const pinLines = pins
    .map((p) => `      <pin digest="SHA-256">${p}</pin>`)
    .join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withSslPinning.js — do not edit by hand.
     Pin set + rotation procedure: docs/RUNBOOK-CERT-ROTATION.md -->
<network-security-config>
  <domain-config>
    <domain includeSubdomains="${includeSubdomains}">${domain}</domain>
    <pin-set expiration="${expiration}">
${pinLines}
    </pin-set>
  </domain-config>
</network-security-config>
`;
}

function withAndroidPinning(config, opts) {
  // 1) Write res/xml/network_security_config.xml
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      const resXmlDir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(resXmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(resXmlDir, 'network_security_config.xml'),
        buildNetworkSecurityXml(opts),
        'utf8',
      );
      return cfg;
    },
  ]);

  // 2) Point <application> at it
  config = withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults?.manifest?.application?.[0];
    if (app) {
      app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    }
    return cfg;
  });

  return config;
}

/**
 * Pure builder for the NSPinnedDomains entry — exported for unit tests
 * because `expo prebuild` cannot generate the iOS project on Windows
 * (the EAS cloud build is the end-to-end verifier for the plist).
 */
function buildPinnedDomainEntry({ includeSubdomains, pins }) {
  return {
    NSIncludesSubdomains: includeSubdomains,
    NSPinnedCAIdentities: pins.map((p) => ({ 'SPKI-SHA256-BASE64': p })),
  };
}

function withIosPinning(config, opts) {
  return withInfoPlist(config, (cfg) => {
    const ats = cfg.modResults.NSAppTransportSecurity ?? {};
    const pinned = ats.NSPinnedDomains ?? {};
    pinned[opts.domain] = buildPinnedDomainEntry(opts);
    ats.NSPinnedDomains = pinned;
    cfg.modResults.NSAppTransportSecurity = ats;
    return cfg;
  });
}

module.exports = function withSslPinning(config, props = {}) {
  if (!pinningEnabled()) return config;
  const opts = { ...DEFAULTS, ...props };
  config = withAndroidPinning(config, opts);
  config = withIosPinning(config, opts);
  return config;
};

// Exported for unit tests (not used by Expo itself).
module.exports.buildNetworkSecurityXml = buildNetworkSecurityXml;
module.exports.buildPinnedDomainEntry = buildPinnedDomainEntry;
module.exports.DEFAULTS = DEFAULTS;
